services:
  # Backend Spring Boot API
  - type: web
    name: betting-api
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/betting-api-1.0.0.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        value: postgresql://postgres:5432/bettingdb
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: postgres
      - key: JWT_SECRET
        generateValue: true
      - key: SERVER_PORT
        value: 8080

  # Frontend Static Site
  - type: web
    name: betting-frontend
    env: static
    buildCommand: echo "Static site - no build needed"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /api/*
        destination: https://betting-api.onrender.com/api/*
    envVars:
      - key: REACT_APP_API_URL
        value: https://betting-api.onrender.com/api 