services:
  # Backend Spring Boot API (Docker)
  - type: web
    name: betting-api
    env: docker
    buildCommand: docker build -t betting-api .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JWT_SECRET
        generateValue: true


  # Frontend Static Site
  - type: web
    name: betting-frontend
    env: static
    buildCommand: echo "Static site - no build needed"
    staticPublishPath: . 
databases:
  - type: postgresql
    name: betting-postgres
    plan: free

